import simpleaudio as sa


delphine_j1 = sa.WaveObject.from_wave_file("noms/delphine_j1.wav")
delphine_j2 = sa.WaveObject.from_wave_file("noms/delphine_j2.wav")
vero_j1 = sa.WaveObject.from_wave_file("noms/vero_j1.wav")
vero_j2 = sa.WaveObject.from_wave_file("noms/vero_j2.wav")
olivier_j1 = sa.WaveObject.from_wave_file("noms/olivier_j1.wav")
olivier_j2 = sa.WaveObject.from_wave_file("noms/olivier_j2.wav")
mathieu_j1 = sa.WaveObject.from_wave_file("noms/mathieu_j1.wav")
mathieu_j2 = sa.WaveObject.from_wave_file("noms/mathieu_j2.wav")
joseline_j1 = sa.WaveObject.from_wave_file("noms/joseline_j1.wav")
joseline_j2 = sa.WaveObject.from_wave_file("noms/joseline_j2.wav")
jacques_j1 = sa.WaveObject.from_wave_file("noms/jacques_j1.wav")
jacques_j2 = sa.WaveObject.from_wave_file("noms/jacques_j2.wav")
henri_j1 = sa.WaveObject.from_wave_file("noms/henri_j1.wav")
henri_j2 = sa.WaveObject.from_wave_file("noms/henri_j2.wav")
greg_j1 = sa.WaveObject.from_wave_file("noms/greg_j1.wav")
greg_j2 = sa.WaveObject.from_wave_file("noms/greg_j2.wav")
enrique_j1 = sa.WaveObject.from_wave_file("noms/enrique_j1.wav")
enrique_j2 = sa.WaveObject.from_wave_file("noms/enrique_j2.wav")
cathy_j1 = sa.WaveObject.from_wave_file("noms/cathy_j1.wav")
cathy_j2 = sa.WaveObject.from_wave_file("noms/cathy_j2.wav")
anna_j1 = sa.WaveObject.from_wave_file("noms/anna_j1.wav")
anna_j2 = sa.WaveObject.from_wave_file("noms/anna_j2.wav")
alice_j1 = sa.WaveObject.from_wave_file("noms/alice_j1.wav")
alice_j2 = sa.WaveObject.from_wave_file("noms/alice_j2.wav")

alerte_reset = sa.WaveObject.from_wave_file("sons/alerte_reset_1.wav")
confirm_reset = sa.WaveObject.from_wave_file("sons/confirm_reset.wav")
mode_lect = sa.WaveObject.from_wave_file("sons/mode_lecture.wav")
mode_del = sa.WaveObject.from_wave_file("sons/mode_suprr.wav")
remise_en_jeu_j1 = sa.WaveObject.from_wave_file("sons/remise_en_jeu_de_j1.wav")
remise_en_jeu_j2 = sa.WaveObject.from_wave_file("sons/remise_en_jeu_de_j2.wav")
selec_j1 = sa.WaveObject.from_wave_file("sons/selec_j1.wav")
selec_j2 = sa.WaveObject.from_wave_file("sons/selec_j2.wav")
suprr_de_j1 = sa.WaveObject.from_wave_file("sons/supression_de_j1.wav")
suprr_de_j2 = sa.WaveObject.from_wave_file("sons/supression_de_j2.wav")
tour_j1_son = sa.WaveObject.from_wave_file("sons/tour_j1.wav")
tour_j2_son = sa.WaveObject.from_wave_file("sons/tour_j2.wav")
victoire_j1 = sa.WaveObject.from_wave_file("sons/victoire_j1.wav")
victoire_j2 = sa.WaveObject.from_wave_file("sons/victoire_j2.wav")
